[package]
name = "actions_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
regex = "1.10.5"
clap = { version = "4.5.7", features = ["derive"] }
