#
# This workflow is ran when called by other workflows. 
#
# It goes through the available workflow .yml files in the caller repository at './github/workflows/' 
# and raises a PR with updated version references for the external dependencies that the workflows use.
#
# It requires a GitHub PAT token inherited from the caller in order to raise a PR.
#

name: Update GitHub Actions Dependencies

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:

  raise-pr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
          sh rustup-init.sh -y --default-toolchain none

      - name: Install updater tool
        run: |
          git clone https://github.com/RazvanBerbece/shared-workflows.git
      
      - name: Update workflow files
        run: |
          : # Use the gh_actions_dep_updater Rust tool to update *all* the .yml files
          cd shared-workflows/utils/gh_actions_dep_updater

          for workflow_filename in ../../../.github/workflows/*; do
            cargo run -- w "$workflow_filename"
          done

      - name: Cleanup resources
        run: |
          rm -r shared-workflows
          rm rustup-init.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.PAT }}
            commit-message: updates Actions dependencies
            committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
            signoff: true
            branch: automated-patches
            delete-branch: true
            title: 'patch: update Actions dependencies'
            body: |
                - Updated present GHA dependencies with latest versions published on their GH repositories
                - Auto-generated by [create-pull-request][1]

                [1]: https://github.com/peter-evans/create-pull-request

                *Note: Keep in mind that these updates don't account for breaking changes between versions, and it's recommended that the
                dependencies' changelogs are verified before pushing anything into production.*
            labels: |
                automated
                gha dependency updates