#
# This workflow is ran when called by other workflows. 
#
# It goes through the available workflow .yml files in the caller repository at './github/workflows/' 
# and raises a PR with updated version references for the external dependencies that the workflows use.
#
# It requires a GitHub PAT token inherited from the caller in order to raise a PR.
#

name: Update GitHub Actions Dependencies

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:

  raise-pr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -y
      
      - name: Update workflow files
        run: |
          : # Use the gh_actions_dep_updater Rust tool to update *all* the .yml files
          for workflow_filename in ./.github/workflows/*; do
            cargo run -- w "$workflow_filename"
          done

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.PAT }}
            commit-message: Updates Actions dependencies
            committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
            author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
            signoff: false
            branch: patches
            delete-branch: true
            title: 'patch: update Actions dependencies'
            body: |
                Updates Actions dependencies
                - Updated with latest
                - Auto-generated by [create-pull-request][1]

                [1]: https://github.com/peter-evans/create-pull-request

                Note: Keep in mind that these updates don't account for breaking changes between versions, and it's recommended that the
                dependencies' changelogs are verified before pushing anything into production.
            labels: |
                automated pr